overrides/theme/content/component.tsx
overrides/theme/hero/component.tsx
stories/theme.AG_.mdx
stories/theme.AQ_.mdx
stories/theme.BIO.mdx
stories/theme.DIS.mdx
stories/theme.ENR.mdx

I added one commit that was needed after resolving the path issue for stories (themes).
I also added one attribute for theme's landing stories `theme: true` : https://github.com/NASA-IMPACT/veda-config-eic/compare/theme_content...NASA-IMPACT:veda-config-eic:edit-theme-content?expand=1#diff-13dab886caaef0a54d79fa35259e1cf2ad277dd38f127136f90edae9b03ce294R7 (Other changes in mdx files are just automatic lint.)

Edit theme content

---

overrides/home/component.tsx

I thought I would just put the pattern that should work using `Fold`.
I hope my change doesn't interfere your workflow!

Fold cards

---

overrides/common/style.ts
overrides/components/home-hero/component.tsx
overrides/components/theme-cards.tsx
overrides/home/component.tsx

Make sure the heading is in descending order + add alt text for hero figure image
I also restyled the header (font-weight, letter spacing - I think there should be some kinds of line-height change too but couldn't figure out the programmatic way to figure this out.) - Flagging that this header change is purely for landing page. I did not introduce this header style to other pages for consistency throughout the pages. 
part of https://github.com/NASA-IMPACT/veda-config-eic/issues/30

Arrange heading structure + heading style

---

custom-pages/teach/index.mdx
custom-pages/visit/index.mdx

Teachm, visit a center as a main nav item. 
Took only necessary changes from https://github.com/NASA-IMPACT/veda-config-eic/pull/24

Put Make Center, Teach as a nav item

---

overrides/common/embedded-video-carousel.tsx
overrides/common/style.ts
overrides/components/theme-cards.tsx

Checking one item in https://github.com/NASA-IMPACT/veda-config-eic/issues/30
Added hover style to theme card + carousel buttons

Add hover style

---

overrides/components/page-footer/component.tsx
overrides/home/component.tsx

Rearranged logo at the footer.
I also put the bottom content part into the grid + moved the background image a little bit.

Style polish

---

overrides/common/embedded-video-carousel.tsx

The recent merge introduced a weird bug on carousel to have multiple buttons. This PR fixes the bug.

Double button on carousel fix

---

datasets/epa-ch4emission-v2express.data.mdx
datasets/geoglam.data.mdx

Dataset overview content updates for
1. geoglam - from https://docs.google.com/document/d/1wayLAQT50Kz_xE5cDqSpfEg6-HUWHeCI1hvUp4oRt3I/edit
2. epa - from https://docs.google.com/document/d/18iEJcleQ1Ps6TszOCPyZ7oHCSASGJEBNF6cVQQNBaoc/edit#heading=h.6e6mm6iranye
Note: This content has been sent for review to the respective data providers and may require minor updates after the review.

Dataset overview updates for GEOGLAM and EPA

---

datasets/grdi-v1.data.mdx
datasets/no2.data.mdx

Dataset overview content updates for
1. GRDI - from https://docs.google.com/document/d/1q0EDmAUf5FU6KN0Y4k1YkC3XSYEqLblsVmDJ3BZMVxU/edit
2. NO2 - from https://docs.google.com/document/d/1YKNUXSbd_2HOt6jHGSFHSh4WZB2IYk_ffFFh2WZH9dU/edit
Note: This content has been sent for review to the respective data providers and may require minor updates after the review.

Update the contents of NO2 and GRDI content pages.

---

overrides/components/page-footer/component.tsx

Editing ghg specific paragraph to eic.

Edit GHG to EIC in disclaimer modal

---

overrides/home/component.tsx

I believe this needs to be updated too, right? @j08lue

Update partner order

---

overrides/home/component.tsx
overrides/home/expand-link.tsx

Fix links on home page

---

custom-pages/teach/index.mdx
overrides/about.mdx

Re https://github.com/NASA-IMPACT/veda-config-eic/issues/45

Fix feedback links on about and teach pages

---

custom-pages/teach/index.mdx
overrides/about.mdx

This publishes major content updates and bug fixes
- #29 
- #51 
- #52 
- #50 
- #49 
and perhaps more.
NB: There may still be open points to address from our launch check list:
- #45

Push to production

---

custom-pages/teach/index.mdx
overrides/about.mdx
overrides/common/embedded-video-carousel.tsx
overrides/common/story-data.ts
overrides/components/page-footer/component.tsx
stories/theme.AG_.introduction_agriculture/carousel_content.json
stories/theme.AG_.mdx
stories/theme.DIS.mdx

Address issues discovered during pre-release review

---

stories/location.HEAD.mdx
stories/theme.ENR.introduction_energy_generation.mdx
stories/theme.SLR.introduction_sea_level_rise.mdx

Replacing links for Sea Level Rise and Sustainable Energy
---
Check the [Content Documentation](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/CONTENT.md) for more details.

Fix minor content issues

---

overrides/about.mdx
overrides/home/component.tsx

Minor copy edits to the splash and about pages requested ASAP. I fiddled with the line breaks on the splash page, @faustoperez, hopefully you agree this is the best way to break it down. I opted to keep the blue highlighting on `one planet` though I do think it's less appropriate in this context since we're not really contrasting any more...

copy-edits from marc etkind

---

overrides/common/style.ts
overrides/components/page-footer/component.tsx
overrides/home/expand-link.tsx

This PR is in place of this closed [PR](https://github.com/NASA-IMPACT/veda-config-eic/pull/63)

[#30] Update general link styles and footer focus and hover states

---

overrides/home/component.tsx

Closes https://github.com/NASA-IMPACT/veda-config-eic/issues/75

[#75] Make GHG Center top visual priority on home page

---

.env
overrides/components/page-footer/component.tsx

Update feedback form urls (#81)

---

stories/location.HEAD.mdx

wrap h2 in <Block> & <Prose> + wrap caption text in <Caption>. Closes #86.

BUGFIX: Figure on Headquarters location page

---

package.json

- Bump version for push to production
- Update `veda-ui` to latest version to get in this fix: https://github.com/NASA-IMPACT/veda-ui/pull/883

Bump version and point to latest main

---

overrides/components/page-footer/component.tsx

Adding a footer link for navigating to NASA's accessibility statement, located at https://www.nasa.gov/accessibility/.

Added link to NASA's accessibility statement

---

package.json

- embed [hyperweb](https://svs.gsfc.nasa.gov/webapps/hyperweb) on `/stories/hyperwall`
- point to v4.2.0 of veda-ui

bump version numbers for new develop -> main merge

---

package.json
stories/teach.ALL.stem_resources.mdx

update url and description to new stem resource library by request from Lin Chambers
---
Check the [Content Documentation](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/CONTENT.md) for more details.

Content: STEM Resources

---

.env
custom-pages/teach/index.mdx
overrides/about.mdx
overrides/components/page-footer/component.tsx
stories/location.HEAD.mdx
stories/locfeature.IMMER.mdx

point to new google form, add language to headquarters and immersive page.

Update Contact Us Form

---

package.json

Bump MAJOR version to 1.0.0

---

overrides/common/story-data.ts
package-lock.json
package.json
stories/theme.AQ_.mdx
stories/theme.SLR.mdx
stories/theme.WTR.mdx
yarn.lock

Merging the changes to Brian's patch

Change URL underscores to hyphens to be consistent

---

stories/locfeature.MCM.mdx

Update the link to mobile climate mapper to be internal one. Needs to be tested on staging if it's going to work properly.

Update the link to mobile climate mapper to internal one

---

stories/locfeature.MCM.mdx

Revert url change

---

stories/location.NMNH.mdx

NMNH card needs to point to the Smithsonian's page, there should not be an internal Earth.gov page. 
https://naturalhistory.si.edu/NASA-EIC

Make NMNH card an external link

---

overrides/components/related-content-cards.tsx
package.json
stories/location.NMNH.mdx
stories/locfeature.MCM.mdx

[PROD] Bump ui version to v5.9.0 and pass new prop to the override component 

---

stories/theme.WLF.mdx

Adding youtube video embed of Wildfires content. PR directly into main for simple content update. 
---
Check the [Content Documentation](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/CONTENT.md) for more details.

Content: youtube video for Wildfires theme

---

overrides/components/visit-slr.tsx

Modify earth.gov/sealevel reference to global sea level rise portal

Update visit-slr.tsx for global slr

---

datasets/cmip6-climdex-tmaxxf-access-cm2.data.mdx

```yaml
rescale: 0,365
```
doesn't work anymore,
updating to
```yaml
rescale:
- 0
- 365
```

Fix rescale values

---

common/styles.scss
overrides/components/header-brand/component.tsx
yarn.lock

merge link fix with USAID update

---

common/styles.scss
overrides/components/header-brand/component.tsx
yarn.lock

- Bump to veda UI 6.2.0
- Pull fix for external links

Bump to 6.2.0, pull fix for external links
