.env, custom-pages/visit/component.tsx, overrides/common/carousel.js, overrides/common/embedded-video-carousel.tsx, package.json, stories/locfeature.HYPER.mdx, yarn.lock
- It is good to keep in mind that users rarely interact with carousels. When vertical space is allowed, it is considered better not to use it: https://www.smashingmagazine.com/2022/04/designing-better-carousel-ux/#do-users-actually-use-carousels 
- The carousel in this pr is not meant for any element, it is specifically for embedded video.
Close #15 
example video carousel:  https://deploy-preview-23--earth-information-center.netlify.app/stories/hyperwall
=> Add Carousel component for embedded video

overrides/common/embedded-video-carousel.tsx
Display current slide number for Carousel. 
Check one item in : https://github.com/NASA-IMPACT/veda-config-eic/issues/30
This is probably not an ideal way to do this (because `DotGroup` component is not really designed for this job, but it just happens to have the props that carousel needs - `currentSlide`), but it is surely a fast way. 
You can see how it looks : https://deploy-preview-33--earth-information-center.netlify.app/stories/hyperwall  
@agurvich ☝️ I hope this helps Carousel experience.
Also, I'd like to note that the keyboard navigation is very difficult with the current Carousel. This raises the accessibility issue.  I did a little bit of tweak hoping that helps keyboard navigation, but not sure if that is enough. Related to the accessibility issue, the slide title in the …
=> Add current slide number/total slide number to carousel 

overrides/home/component.tsx, overrides/home/partners.tsx
Related to https://github.com/NASA-IMPACT/veda-config-eic/issues/30
=> [#30] Updated logos to follow design 

overrides/components/page-footer/component.tsx
Add 'Contact us' which is a link to Google Form to the footer.
🤚  This does not open the feedback form in the modal. This transitions the page to Google form page.
=> Add google form link only to footer

overrides/common/style.ts, overrides/components/theme-cards.tsx, overrides/theme/content/component.tsx
@sandrahoang686  In case you are touching the same file, I changed the `focusStyle` from `common/style` to have primary color outline. I left out `hoverStyle` even though themeCard doesn't use it anymore.  Let's clean out after? 😬 
@faustoperez  As I mentioned in the issue, it is not straightforward to style the story card from the instance side. I left that style out.
=> Change hover,focus style for theme card, add screen reader only heading

overrides/components/theme-cards.tsx
The main page theme card components return 404 for now because of the incorrect link structure. This PR fixes it.
=> Fix theme card link

datasets/cmip6-climdex-tmaxxf-access-cm2.data.mdx
We're using "theme" instead of "topics" in EIC site-wide
=> Rename topics to theme

.env
Removing trailing slashes in the API urls that was causing issue with analysis
=> Remove trailing slash from api urls

datasets/cmip6-climdex-tmaxxf-access-cm2.data.mdx, datasets/co2.mdx, datasets/ecco-sea-surface-height.mdx, datasets/geoglam.data.mdx, datasets/grdi-v1.data.mdx, datasets/hls-ej.mdx, datasets/land-cover.mdx, datasets/new-urbanization.mdx, datasets/no2.data.mdx, datasets/ocean-npp.mdx, datasets/oco2-mip-co2budget.mdx, datasets/population-density.mdx, datasets/so2.mdx, datasets/soilmoisture-volumetric.mdx, datasets/stream-network.mdx, datasets/svi_overall.mdx, datasets/tws-lis.mdx
When running zonal statistics analyses, the app by default shows all statistics on the same y-axis (mean, standard deviation, min, max, median). This is rarely useful and something we are going to address in the future.
e.g. consider the left vs the right view
Until we implemented nicer charts, we can get better default views by setting the default metric to show to `mean` (continuous variables) or `median` (categorical).
That's done in this PR for all the EIC datasets.
=> Add default analysis metric to all datasets

stories/locfeature.IMMER.mdx
Replace all of the static images with embedded youtube videos that loop. 
---
Check the [Content Documentation](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/CONTENT.md) for more details.
=> Content: Replace images with embedded youtube videos

stories/theme.AQ_.mdx
We are moving to sunset the 
https://gis.earthdata.nasa.gov/portal/apps/sites/#/earth-information-center/
website. This block references content that we no longer want to point to (nor need to replicate).
_Replace with brief description of the update and why it is needed. Link to relevant issues._
_Replace with instructions on how this change be tested/verified._
=> Update theme.AQ_.mdx to remove link to old ESRI site

.env
Add DAP tracking code for federal websites.
After deployed, inspect elements, find the dap tracking code there.
Depends on https://github.com/NASA-IMPACT/veda-config-eic/pull/93
=> Add DAP tracking code

stories/locfeature.HYPER.mdx
Changing url to explicitly include `index.html` so it embeds correctly, see current state of `staging.earth.gov/stories/hyperwall`:
Still working on getting approval for a deploy preview domain name so unfortunately testing has to be done on `staging.earth.gov` which means we need to merge to `develop` to see if it works. I'm really sorry folks... I promise we won't make a habit of this, I will try and get a deploy preview domain sorted so that we can test this on the auto-generated previews in the future but I don't think I can get it done on a turnaround time of ~1 day.
=> change hyperweb embed url to explicitly include index.html

stories/locfeature.HYPER.mdx
i accidentally had my browser set to 125% zoom and so I didn't notice there was a ton of empty padding underneath the embedded hyperweb content.
=> fix height calculation (previously I had my browser set to 125% zoom, sorry :( )

stories/locfeature.HYPER.mdx
this change shrinks the height of the hyperweb embed iframe to avoid extra whitespace. 
not sure why it appeared to work originally. perhaps some kind of cache issue.
before (live on Earth.gov): 
(ignore frames that are gray, they are CSP issues with Worldview and I've already sent them an email)
after: 
(ignore frames that are gray, I didn't setup my reverse proxy so they are CSP issues with localhost)
check that it looks right on staging.earth.gov but @slesaad  and I did that with the last one and I feel like I'm going crazy because it looked fine to me. That's why I suspect a cache issue.
@hanbyul-here  can you have a look at the height calculation and let me know if there's an intelligent way to do it that actually measures the height of the framed content rather than guessing?
=> HOTFIX: replace height calculation

overrides/components/visit-ghg.tsx
U.S. GHG Center -> US GHG Center (based on official GHG conventions)
The blue button on the home page for visit GHG Center should say US GHG Center instead of U.S. GHG Center
=> Fix US GHG Center shortform typo

.env, datasets/epa-ch4emission-v2express.data.mdx
Linked PR: https://github.com/NASA-IMPACT/veda-ui/issues/1019
- Base STAC API and Raster API urls updated for production openveda.cloud
- GHG center STAC and Raster API urls updated to align with recent GHG path changes unrelated to openveda.cloud
To migrate the Dashboard usage of VEDA backend APIs to new production openveda.cloud VEDA instance.
Steps taken to validate the new production VEDA instance are documented [here](https://github.com/NASA-IMPACT/veda-architecture/issues/441).
=> feat: migrate to production veda stac catalog and titiler AND update GHG URLs

overrides/common/story-data.ts, stories/locfeature.HOMETOWN.mdx
move feature card out of related applications of hometown dashboard and into the feature card section.
=> move mobile climate mapper to the features section

overrides/components/related-content-cards.tsx, package.json, stories/locfeature.MCM.mdx
1. Bump the UI version to v5.9.0
2. Pass in the new `hideExternalLinkBadge` prop to the related content override
3. Use the new `hideExternalLinkBadge` for the Mobile Climate Mapper card to hide the "External Link" badge for the card (the MCM card is shown under the `Visit a Center` link in the footer)
=> Bump ui version to v5.9.0 and pass new prop to the override component

common/styles.scss, overrides/home/carousel/carousel-item.tsx, overrides/home/carousel/index.scss, overrides/home/carousel/index.tsx, overrides/home/carousel/items.js, overrides/home/component.tsx, package.json, yarn.lock
This PR introduces the configurable carousel component to the EIC instance. [Example](https://deploy-preview-147--earth-information-center.netlify.app/) of the Carousel shown on the home page.
Usage:
1. The <Carousel> component can be simply imported and used as shown [here](https://github.com/NASA-IMPACT/veda-config-eic/pull/147/files#diff-0e4e8d741403aeb3774c5873685c7a9c24525eccf746c56c408186cb5f0f14f6R115).
2. Each carousel card is customizable through the [config file](https://github.com/NASA-IMPACT/veda-config-eic/pull/148/files#diff-1335d174ce435a4f2cb6cbf16352aee0ad6ea5f9c2bc68c69ce0717bb088bbfb). I've included examples in the config file to showcase linking to internal/external routes and image usage for each card
=> Port the carousel feature to EIC

stories/theme.SLR.mdx
EIC video producers created a new narrated video that needs to be added to the SLR theme page in line with the other narrated videos. 
Visit the page and see if the Youtube video is embedded correctly.
=> add new narrated video to slr theme page

.github/workflows/checks.yml, .github/workflows/deploy.yml
Some of the actions we're using are [deprecated](https://github.com/NASA-IMPACT/veda-config-eic/actions/runs/13267931177/job/37040024802), so I took the opportunity to upgrade all of them.
=> Upgrade github action versions

.veda/veda, common/styles.scss, package.json, postcss.config.js, styles/_uswds-theme.scss, styles/theme.scss, yarn.lock
Related issue: https://github.com/NASA-IMPACT/veda-ui/issues/1556
Starting from veda-ui v6.0.0, the Veda UI now expects USWDS (U.S. Web Design System) theming and styles to be provided by the implementing instance rather than bundled with the library. This offers two key benefits, 1) custom theming where each instance can now implement its own theming for USWDS components and 2) reduced bundle size of the veda-ui library
This PR sets up the necessary theming pipeline.
=> USWDS theming pipeline setup, bump veda-UI to v6.1.1
